
LANG_MAP = {
    "繁體中文": {
        "開始錄製": "開始錄製",
        "暫停/繼續": "暫停/繼續",
        "停止": "停止",
        "回放": "回放",
        "MiniMode": "MiniMode",
        "Script路徑": "Script路徑",
        "快捷鍵": "快捷鍵",
        "關於": "關於",
        "重複次數:": "重複次數:",
        "重複時間": "重複時間",
        "Script:": "Script:",
        "重新命名": "重新命名",
        "合併腳本": "合併腳本",
        "Script": "Script",
        "合併並儲存": "合併並儲存",
        "所有Script": "所有Script",
        "新Script名稱：": "新Script名稱：",
        "確定": "確定",
        "清空": "清空",
        "加入": "加入",
        "移除": "移除",
        "延遲秒數:": "延遲秒數:",
        "Language": "Language",
        "回放速度:": "回放速度:",
        "總運作": "總運作",
        "單次": "單次",
        "錄製": "錄製",
        "刪除": "刪除",
        "儲存": "儲存",
        "重複間隔": "重複間隔",
        "剩餘": "剩餘",
        "強制停止": "強制停止",
        # 腳本編輯器
        "新增動作": "新增動作",
        "執行": "執行",
        "載入": "載入",
        "同步": "同步",
        "語法說明": "語法說明",
        "動作列表：": "動作列表：",
        "序": "序",
        "指令": "指令",
        "參數": "參數",
        "延遲(ms)": "延遲(ms)",
        "執行輸出：": "執行輸出：",
        "選擇指令：": "選擇指令：",
        "範例: move_to → 100, 200 | type_text → Hello": "範例: move_to → 100, 200 | type_text → Hello",
        "延遲(1000=1秒)後執行：": "延遲(1000=1秒)後執行：",
        "取消": "取消",
        "關閉": "關閉",
        # 主程式UI
        "隨機": "隨機",
        "腳本選單:": "腳本選單:",
        "選擇視窗": "選擇視窗",
        "腳本名稱": "腳本名稱",
        "捕捉快捷鍵：": "捕捉快捷鍵：",
        "設定快捷鍵": "設定快捷鍵",
        "開啟資料夾": "開啟資料夾",
        "刪除腳本": "刪除腳本",
        "腳本編輯器": "腳本編輯器",
        # 視窗狀態對話框
        "強制歸位並回放": "強制歸位並回放",
        "保持當前位置回放": "保持當前位置回放",
        "取消回放": "取消回放",
        "視窗狀態不符": "視窗狀態不符",
        "錄製時的視窗": "錄製時的視窗",
        "當前視窗": "當前視窗",
        "位置": "位置",
        "大小": "大小",
        "選項說明": "選項說明",
        # 其他
        "ChroLens 腳本編輯器": "ChroLens 腳本編輯器",
        "ChroLens 腳本語法說明": "ChroLens 腳本語法說明",
        # 選單和列表
        "清除": "清除",
        "加入至腳本": "加入至腳本",
        "從腳本移除": "從腳本移除",
        "重新命名腳本": "重新命名腳本",
        "腳本列表": "腳本列表",
        # 進階功能
        "自動切換": "自動切換",
        "勾選時，程式錄製/回放將自動轉換": "勾選時，程式錄製/回放將自動轉換",
        "滑鼠模式": "滑鼠模式",
        "勾選時以控制真實滑鼠的模式回放": "勾選時以控制真實滑鼠的模式回放",
        # 選單標題
        "1.日誌顯示": "1.日誌顯示",
        "2.腳本設定": "2.腳本設定",
        "3.整體設定": "3.整體設定",
        # 編輯器專用
        "截圖辨識": "截圖辨識",
        "範圍辨識": "範圍辨識",
        "OCR辨識": "OCR辨識",
        "滑鼠錄製": "滑鼠錄製",
        "進階編輯": "進階編輯",
        "基本指令": "基本指令",
        "圖片辨識": "圖片辨識",
        "條件判斷": "條件判斷",
        "迴圈控制": "迴圈控制",
        "請輸入指令": "請輸入指令",
        "儲存成功": "儲存成功",
        "載入成功": "載入成功",
        "執行成功": "執行成功",
        # 視窗操作
        "取得視窗標題": "取得視窗標題",
        "設定視窗大小": "設定視窗大小",
        "最小化視窗": "最小化視窗",
        "最大化視窗": "最大化視窗",
        "還原視窗": "還原視窗",
        # 剪貼簿
        "複製到剪貼簿": "複製到剪貼簿",
        "從剪貼簿讀取": "從剪貼簿讀取",
        "清空剪貼簿": "清空剪貼簿",
        # 螢幕擷取
        "截圖全螢幕": "截圖全螢幕",
        "截圖區域": "截圖區域",
        "截圖視窗": "截圖視窗",
        # 編輯器UI
        "文字指令編輯器": "文字指令編輯器",
        "重新載入": "重新載入",
        "自訂模組": "自訂模組",
        "儲存新模組": "儲存新模組",
        "插入模組": "插入模組",
        "已儲存的模組": "已儲存的模組",
        "雙擊插入": "雙擊插入",
        "摺疊軌跡顯示": "摺疊軌跡顯示",
        "模組內容預覽": "模組內容預覽",
        "就緒": "就緒",
        # 指令說明
        "ChroLens 指令參考": "ChroLens 指令參考",
        "已複製": "已複製",
        "點擊指令即自動複製到剪貼簿": "💡 點擊指令即自動複製到剪貼簿",
        "提示說明": "提示：指令中的 T= 參數表示執行時間",
        "基本操作": "基本操作",
        "圖片辨識指令": "圖片辨識指令",
        "滑鼠操作": "滑鼠操作",
        "鍵盤操作": "鍵盤操作",
        "流程控制": "流程控制",
        "OCR文字辨識": "OCR文字辨識",
        "延遲控制": "延遲控制",
        "變數系統": "變數系統",
        "循環控制": "循環控制",
        "多條件判斷": "多條件判斷",
        "隨機功能": "隨機功能",
        "計數器與計時器": "計數器與計時器",
        # 對話框
        "請選擇腳本": "請選擇腳本",
        "確定要刪除嗎": "確定要刪除嗎？",
        "刪除成功": "刪除成功",
        "請輸入模組名稱": "請輸入模組名稱",
        "模組名稱不能為空": "模組名稱不能為空",
        "模組已存在": "模組已存在",
        "請輸入名稱": "請輸入名稱",
        "名稱不能為空": "名稱不能為空",
        # 狀態訊息
        "正在準備截圖": "正在準備截圖...",
        "拖曳滑鼠選取要辨識的區域": "拖曳滑鼠選取要辨識的區域 (ESC取消)",
        "截圖成功": "截圖成功",
        "已儲存到images資料夾": "已儲存到images資料夾",
        "處理中": "處理中...",
        "載入中": "載入中...",
        # 錯誤訊息
        "找不到圖片": "找不到圖片",
        "載入失敗": "載入失敗",
        "儲存失敗": "儲存失敗",
        "格式錯誤": "格式錯誤",
        "無法開啟檔案": "無法開啟檔案",
        "腳本不存在": "腳本不存在",
        # 確認對話框
        "警告": "警告",
        "錯誤": "錯誤",
        "成功": "成功",
        "資訊": "資訊"
    },
    "日本語": {
        "開始錄製": "録画開始",
        "暫停/繼續": "一時停止 / 再開",
        "停止": "停止",
        "回放": "再生",
        "MiniMode": "ミニモード",
        "Script路徑": "Scriptのパス",
        "快捷鍵": "ホットキー",
        "關於": "アバウト",
        "重複次數:": "繰り返し回数：",
        "重複時間": "間隔時間",
        "Script:": "Script：",
        "重新命名": "名前を変更",
        "合併腳本": "スクリプト結合",
        "Script": "Script",
        "合併並儲存": "結合して保存",
        "所有Script": "全Script",
        "新Script名稱：": "新しい名前：",
        "確定": "OK",
        "清空": "クリア",
        "加入": "追加",
        "移除": "削除",
        "延遲秒數:": "ディレイ（秒）：",
        "Language": "言語",
        "回放速度:": "再生速度：",
        "總運作": "総再生",
        "單次": "1回のみ",
        "錄製": "録画",
        "刪除": "削除",
        "儲存": "保存",
        "重複間隔": "繰り返し間隔",
        "剩餘": "残り",
        "強制停止": "強制停止",
        # 腳本編輯器
        "新增動作": "アクション追加",
        "執行": "実行",
        "載入": "ロード",
        "同步": "同期",
        "語法說明": "構文説明",
        "動作列表：": "アクションリスト：",
        "序": "番号",
        "指令": "コマンド",
        "參數": "パラメータ",
        "延遲(ms)": "遅延(ms)",
        "執行輸出：": "実行出力：",
        "選擇指令：": "コマンド選択：",
        "範例: move_to → 100, 200 | type_text → Hello": "例: move_to → 100, 200 | type_text → Hello",
        "延遲(1000=1秒)後執行：": "遅延(1000=1秒)後実行：",
        "取消": "キャンセル",
        "關閉": "閉じる",
        # 主程式UI
        "隨機": "ランダム",
        "腳本選單:": "スクリプトメニュー：",
        "選擇視窗": "ウィンドウ選択",
        "腳本名稱": "スクリプト名",
        "捕捉快捷鍵：": "ホットキー捕捉：",
        "設定快捷鍵": "ホットキー設定",
        "開啟資料夾": "フォルダを開く",
        "刪除腳本": "スクリプト削除",
        "腳本編輯器": "スクリプトエディタ",
        # 視窗狀態對話框
        "強制歸位並回放": "強制移動して再生",
        "保持當前位置回放": "現在位置で再生",
        "取消回放": "再生キャンセル",
        "視窗狀態不符": "ウィンドウ状態不一致",
        "錄製時的視窗": "録画時のウィンドウ",
        "當前視窗": "現在のウィンドウ",
        "位置": "位置",
        "大小": "サイズ",
        "選項說明": "オプション説明",
        # 其他
        "ChroLens 腳本編輯器": "ChroLens スクリプトエディタ",
        "ChroLens 腳本語法說明": "ChroLens 構文説明",
        # 選單和列表
        "清除": "クリア",
        "加入至腳本": "スクリプトに追加",
        "從腳本移除": "スクリプトから削除",
        "重新命名腳本": "名前を変更",
        "腳本列表": "スクリプトリスト",
        # 進階功能
        "自動切換": "自動切替",
        "勾選時，程式錄製/回放將自動轉換": "チェック時、録画/再生は自動的にミニモードに切り替わります",
        "滑鼠模式": "マウスモード",
        "勾選時以控制真實滑鼠的模式回放": "チェック時、実際のマウスを制御して再生します",
        # 選單標題
        "1.日誌顯示": "1.ログ表示",
        "2.腳本設定": "2.スクリプト設定",
        "3.整體設定": "3.全体設定",
        # 編輯器専用
        "截圖辨識": "スクリーンショット認識",
        "範圍辨識": "範囲認識",
        "OCR辨識": "OCR認識",
        "滑鼠錄製": "マウス録画",
        "進階編輯": "高度編集",
        "基本指令": "基本コマンド",
        "圖片辨識": "画像認識",
        "條件判斷": "条件分岐",
        "迴圈控制": "ループ制御",
        "請輸入指令": "コマンドを入力",
        "儲存成功": "保存成功",
        "載入成功": "ロード成功",
        "執行成功": "実行成功",
        # ウィンドウ操作
        "取得視窗標題": "ウィンドウタイトル取得",
        "設定視窗大小": "ウィンドウサイズ設定",
        "最小化視窗": "最小化",
        "最大化視窗": "最大化",
        "還原視窗": "元に戻す",
        # クリップボード
        "複製到剪貼簿": "クリップボードにコピー",
        "從剪貼簿讀取": "クリップボードから読取",
        "清空剪貼簿": "クリップボードをクリア",
        # スクリーンショット
        "截圖全螢幕": "全画面スクリーンショット",
        "截圖區域": "範囲スクリーンショット",
        "截圖視窗": "ウィンドウスクリーンショット"
    },
    "English": {
        "開始錄製": "Start Recording",
        "暫停/繼續": "Pause/Resume",
        "停止": "Stop",
        "回放": "Play",
        "MiniMode": "Mini Mode",
        "Script路徑": "Script Path",
        "快捷鍵": "Hotkey",
        "關於": "About",
        "重複次數:": "Repeat:",
        "重複時間": "Interval",
        "Script:": "Script:",
        "重新命名": "Rename",
        "合併腳本": "Merge Scripts",
        "Script": "Script",
        "合併並儲存": "Merge & Save",
        "所有Script": "All Scripts",
        "新Script名稱：": "New Script Name:",
        "確定": "Confirm",
        "清空": "Clear",
        "加入": "Add",
        "移除": "Remove",
        "延遲秒數:": "Delay (sec):",
        "Language": "Language",
        "回放速度:": "Playback Speed:",
        "總運作": "Total Runs",
        "單次": "Single Run",
        "錄製": "Record",
        "刪除": "Delete",
        "儲存": "Save",
        "重複間隔": "Repeat Interval",
        "剩餘": "Remain",
        "強制停止": "Force Quit",
        # Script Editor
        "新增動作": "Add Action",
        "執行": "Execute",
        "載入": "Load",
        "同步": "Sync",
        "語法說明": "Syntax Help",
        "動作列表：": "Action List:",
        "序": "No.",
        "指令": "Command",
        "參數": "Parameters",
        "延遲(ms)": "Delay(ms)",
        "執行輸出：": "Execution Output:",
        "選擇指令：": "Select Command:",
        "範例: move_to → 100, 200 | type_text → Hello": "Example: move_to → 100, 200 | type_text → Hello",
        "延遲(1000=1秒)後執行：": "Execute after delay (1000=1s):",
        "取消": "Cancel",
        "關閉": "Close",
        # Main UI
        "隨機": "Random",
        "腳本選單:": "Script Menu:",
        "選擇視窗": "Select Window",
        "腳本名稱": "Script Name",
        "捕捉快捷鍵：": "Capture Hotkey:",
        "設定快捷鍵": "Set Hotkey",
        "開啟資料夾": "Open Folder",
        "刪除腳本": "Delete Script",
        "腳本編輯器": "Script Editor",
        # Window State Dialog
        "強制歸位並回放": "Force Reposition & Play",
        "保持當前位置回放": "Keep Current Position",
        "取消回放": "Cancel Playback",
        "視窗狀態不符": "Window State Mismatch",
        "錄製時的視窗": "Window at Recording",
        "當前視窗": "Current Window",
        "位置": "Position",
        "大小": "Size",
        "選項說明": "Option Description",
        # Others
        "ChroLens 腳本編輯器": "ChroLens Script Editor",
        "ChroLens 腳本語法說明": "ChroLens Syntax Help",
        # Menu and List
        "清除": "Clear",
        "加入至腳本": "Add to Script",
        "從腳本移除": "Remove from Script",
        "重新命名腳本": "Rename Script",
        "腳本列表": "Script List",
        # Advanced Features
        "自動切換": "Auto Switch",
        "勾選時，程式錄製/回放將自動轉換": "When checked, recording/playback will auto-switch to Mini Mode",
        "滑鼠模式": "Mouse Mode",
        "勾選時以控制真實滑鼠的模式回放": "When checked, playback will control the real mouse cursor",
        # Menu Titles
        "1.日誌顯示": "1.Log Display",
        "2.腳本設定": "2.Script Settings",
        "3.整體設定": "3.Global Settings",
        # Editor Specific
        "截圖辨識": "Screenshot Recognition",
        "範圍辨識": "Area Recognition",
        "OCR辨識": "OCR Recognition",
        "滑鼠錄製": "Record Mouse",
        "進階編輯": "Advanced Edit",
        "基本指令": "Basic Commands",
        "圖片辨識": "Image Recognition",
        "條件判斷": "Conditional Logic",
        "迴圈控制": "Loop Control",
        "請輸入指令": "Enter command",
        "儲存成功": "Saved successfully",
        "載入成功": "Loaded successfully",
        "執行成功": "Executed successfully",
        # Window Operations
        "取得視窗標題": "Get Window Title",
        "設定視窗大小": "Set Window Size",
        "最小化視窗": "Minimize Window",
        "最大化視窗": "Maximize Window",
        "還原視窗": "Restore Window",
        # Clipboard
        "複製到剪貼簿": "Copy to Clipboard",
        "從剪貼簿讀取": "Read from Clipboard",
        "清空剪貼簿": "Clear Clipboard",
        # Screenshot
        "截圖全螢幕": "Screenshot Fullscreen",
        "截圖區域": "Screenshot Area",
        "截圖視窗": "Screenshot Window",
        # Editor UI
        "文字指令編輯器": "Text Command Editor",
        "重新載入": "Reload",
        "自訂模組": "Custom Modules",
        "儲存新模組": "Save New Module",
        "插入模組": "Insert Module",
        "已儲存的模組": "Saved Modules",
        "雙擊插入": "Double-click to insert",
        "摺疊軌跡顯示": "Fold Trajectories",
        "模組內容預覽": "Module Preview",
        "就緒": "Ready",
        # Command Reference
        "ChroLens 指令參考": "ChroLens Command Reference",
        "已複製": "Copied",
        "點擊指令即自動複製到剪貼簿": "💡 Click command to copy to clipboard",
        "提示說明": "Tip: T= parameter indicates execution time",
        "基本操作": "Basic Commands",
        "圖片辨識指令": "Image Recognition",
        "滑鼠操作": "Mouse Operations",
        "鍵盤操作": "Keyboard Operations",
        "流程控制": "Flow Control",
        "OCR文字辨識": "OCR Text Recognition",
        "延遲控制": "Delay Control",
        "變數系統": "Variable System",
        "循環控制": "Loop Control",
        "多條件判斷": "Multi-Condition Logic",
        "隨機功能": "Random Features",
        "計數器與計時器": "Counters & Timers",
        # Dialog Messages
        "請選擇腳本": "Please select a script",
        "確定要刪除嗎": "Are you sure to delete?",
        "刪除成功": "Deleted successfully",
        "請輸入模組名稱": "Enter module name",
        "模組名稱不能為空": "Module name cannot be empty",
        "模組已存在": "Module already exists",
        "請輸入名稱": "Enter name",
        "名稱不能為空": "Name cannot be empty",
        # Status Messages
        "正在準備截圖": "Preparing screenshot...",
        "拖曳滑鼠選取要辨識的區域": "Drag mouse to select area (Press ESC to cancel)",
        "截圖成功": "Screenshot captured",
        "已儲存到images資料夾": "Saved to images folder",
        "處理中": "Processing...",
        "載入中": "Loading...",
        # Error Messages
        "找不到圖片": "Image not found",
        "載入失敗": "Load failed",
        "儲存失敗": "Save failed",
        "格式錯誤": "Format error",
        "無法開啟檔案": "Cannot open file",
        "腳本不存在": "Script does not exist",
        # Confirmation Dialogs
        "警告": "Warning",
        "錯誤": "Error",
        "成功": "Success",
        "資訊": "Information"
    }
}

def get_lang_map(lang_key: str):
    """回傳指定語言的字典，預設為繁體中文"""
    return LANG_MAP.get(lang_key, LANG_MAP["繁體中文"])
